# on: [push, pull_request, workflow_dispatch]
name: Build ZMK firmware
on:
  workflow_dispatch: # can be triggered manually
  push:
    paths:
      - "build.yaml"
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/*.conf"
      - "config/west.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
